{"name": "Проверка на переход по клику на \"Восстановить\" пароль на странице логина", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <tests.test_recov_pasw.TestPersonalAcc object at 0x0000026DBE242990>, driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"ce6c1ce9-0f21-4147-b8d9-5fa927361af3\")>\n\n    @allure.title('Проверка на переход по клику на \"Восстановить\" пароль на странице логина')\n    def test_go_to_password_recovery_page_by_clicking_recover_password_link(self, driver):\n        login_page = PswdPage(driver)\n>       login_page.click_recovery_button()\n\ntests\\test_recov_pasw.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\recov_pswd_page.py:17: in click_recovery_button\n    self.click_on_element(ResetPswdLocators.BUTTON_RESET)\npages\\base_page.py:23: in click_on_element\n    element = self.find_element_with_wait(locator)\npages\\base_page.py:18: in find_element_with_wait\n    WebDriverWait(self.driver, 15).until(EC.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"ce6c1ce9-0f21-4147-b8d9-5fa927361af3\")>, method = <function visibility_of_element_located.<locals>._predicate at 0x0000026DBE438720>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "steps": [{"name": "Нажать Восстановить", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\Desktop\\Auto QA\\Diplom\\Diplom_3.0.0\\pages\\recov_pswd_page.py\", line 17, in click_recovery_button\n    self.click_on_element(ResetPswdLocators.BUTTON_RESET)\n  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\Desktop\\Auto QA\\Diplom\\Diplom_3.0.0\\pages\\base_page.py\", line 23, in click_on_element\n    element = self.find_element_with_wait(locator)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\Desktop\\Auto QA\\Diplom\\Diplom_3.0.0\\pages\\base_page.py\", line 18, in find_element_with_wait\n    WebDriverWait(self.driver, 15).until(EC.visibility_of_element_located(locator))\n  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Нажать на элемент", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\Desktop\\Auto QA\\Diplom\\Diplom_3.0.0\\pages\\base_page.py\", line 23, in click_on_element\n    element = self.find_element_with_wait(locator)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\Desktop\\Auto QA\\Diplom\\Diplom_3.0.0\\pages\\base_page.py\", line 18, in find_element_with_wait\n    WebDriverWait(self.driver, 15).until(EC.visibility_of_element_located(locator))\n  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Найти элемент с ожиданием", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\Desktop\\Auto QA\\Diplom\\Diplom_3.0.0\\pages\\base_page.py\", line 18, in find_element_with_wait\n    WebDriverWait(self.driver, 15).until(EC.visibility_of_element_located(locator))\n  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "['xpath', '//button[text()=\"Восстановить\"]']"}], "start": 1730056515526, "stop": 1730056530627}], "parameters": [{"name": "locator", "value": "['xpath', '//button[text()=\"Восстановить\"]']"}], "start": 1730056515526, "stop": 1730056530627}], "start": 1730056515526, "stop": 1730056530627}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1730056515526, "stop": 1730056530627, "uuid": "2f8b670d-ba63-469e-970b-ca38c3c0ca72", "historyId": "fb2ff34092802027e95aab0b68552510", "testCaseId": "78940d99137088a693e79e45c45ede89", "fullName": "tests.test_recov_pasw.TestPersonalAcc#test_go_to_password_recovery_page_by_clicking_recover_password_link", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_recov_pasw"}, {"name": "subSuite", "value": "TestPersonalAcc"}, {"name": "host", "value": "DESKTOP-TS1EIDP"}, {"name": "thread", "value": "9664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_recov_pasw"}]}